# https://pre-commit.com
repos:
  - repo: local
    hooks:
      - id: remove-terraform-lock
        name: Remove .terraform.lock.hcl
        language: system
        entry: rm -f .terraform.lock.hcl
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.1
    hooks:
    - id: tfsec-system

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-system
        args: [.]
