formatter: markdown table

output:
  file: README.md
  mode: inject

content: |-
  ## Example

  <!-- x-release-please-start-version -->

  If you want to use the module in your terraform code, please use a versioned reference:

  ```
  source = "git::https://github.com/Vitesco-Technologies/terraform-module-qip-address?ref=v0.0.0"
  ```

  <!-- x-release-please-end -->

  ```terraform
  {{ include "examples/simple/main.tf" | replace "../.." "git::https://github.com/Vitesco-Technologies/terraform-module-qip-address" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}
