formatter: markdown table

output:
  file: README.md
  mode: inject

content: |-
  ## Example

  ```terraform
  {{ include "examples/simple/main.tf" | replace "../.." "git::https://github.com/Vitesco-Technologies/terraform-module-qip-address" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}
