name: Terraform format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-fmt:
    runs-on: [self-hosted,cloudplatforms]
    # TODO: github.com
    # runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '< 2'

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -no-color -check -diff
